# Debug features for developers
game.debug.enabled=false
game.debug.skip.intro=false

# Default window dimensions
ui.window.default.width=900
ui.window.default.height=620

# Minimum useable layout dimensions
ui.window.min.width=600
ui.window.min.height=400

# resize margin
ui.window.resize.margin=6

# Player starting stats
# TODO implement when adding
game.player.max.health=100
game.player.starting.health=100
game.player.starting.gold=0